# Generated by Django 4.1.4 on 2022-12-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profile_user_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='00000', max_length=200),
            preserve_default=False,
        ),
    ]
